version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
      time: "10:00"
      timezone: America/Toronto
    open-pull-requests-limit: 5
    versioning-strategy: increase-if-necessary
    commit-message:
      prefix: deps
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
    groups:
      production-compatible:
        dependency-type: production
        update-types:
          - minor
          - patch
      development-compatible:
        dependency-type: development
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
      time: "10:30"
      timezone: America/Toronto
    open-pull-requests-limit: 3
    commit-message:
      prefix: ci
    groups:
      github-actions:
        patterns:
          - "*"
